# Generated by Django 4.2 on 2023-05-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_list',
            fields=[
                ('Blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('Blog_title', models.CharField(max_length=300)),
                ('Auther_name', models.CharField(max_length=300)),
                ('Published_date', models.DateTimeField()),
                ('Blog_category', models.CharField(max_length=300)),
                ('Blog_caption', models.CharField(max_length=500)),
                ('Blog_img', models.ImageField(upload_to='blogs')),
            ],
        ),
    ]
