# Generated by Django 4.2 on 2023-06-02 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_list',
            old_name='Blog_img',
            new_name='Blog_image',
        ),
    ]
