# Generated by Django 4.2 on 2023-06-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_rename_blog_img_blog_list_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_list',
            name='Blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
