# Generated by Django 4.2 on 2023-06-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_blog_list_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_list',
            name='Blog_image',
        ),
    ]
