# Generated by Django 4.2 on 2023-06-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_remove_blog_list_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_list',
            name='Blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
