# Generated by Django 4.2 on 2023-08-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_bloglist_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='Blog_category',
            field=models.CharField(blank=True, choices=[('NT', 'Nature'), ('FS', 'Fashion&styles'), ('BS', 'Bussiness'), ('SO', 'Social'), ('TR', 'Travel'), ('FD', 'Food'), ('CL', 'culture')], default='SO', max_length=200, null=True),
        ),
    ]
