# Generated by Django 4.2 on 2023-08-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_alter_bloglist_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='Blog_category',
            field=models.CharField(choices=[('Nature', 'Nature'), ('Fashion', 'Fashion&styles'), ('Business', 'Business'), ('Social', 'Social'), ('Travel', 'Travel'), ('Food', 'Food'), ('Culture', 'Culture')], default='SO', max_length=200),
        ),
    ]
