# Generated by Django 4.2 on 2023-08-16 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_alter_bloglist_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglist',
            name='Blog_category',
            field=models.CharField(choices=[('Fashion', 'Fashion&styles'), ('Business', 'Business'), ('Social', 'Social'), ('Travel', 'Travel'), ('Food', 'Food'), ('Culture', 'Culture'), ('Nature', 'Nature')], default='SO', max_length=200),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorname', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.bloglist')),
            ],
        ),
    ]
